# Generated by Django 4.1.2 on 2022-11-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_product_isbought"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="boughtBy",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
