# Generated by Django 4.1.2 on 2022-10-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
