# Generated by Django 4.1.2 on 2022-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_product_brand_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.DeleteModel(name="AuctionItem",),
    ]
