# Generated by Django 4.1.2 on 2022-12-01 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_product_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="when",
            field=models.DateTimeField(default=datetime.date(2022, 12, 1)),
        ),
    ]
