# Generated by Django 4.1.2 on 2022-12-01 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_product_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="when",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
