# Generated by Django 4.1.2 on 2022-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_product_when"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="milliseconds",
            field=models.IntegerField(default=0),
        ),
    ]
