# Generated by Django 4.1.2 on 2022-12-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_product_milliseconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="milliseconds",
            field=models.BigIntegerField(default=0),
        ),
    ]
