# Generated by Django 4.1.2 on 2022-12-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_product_milliseconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isAdmin",
            field=models.BooleanField(default=False),
        ),
    ]
