# Generated by Django 4.1.2 on 2022-12-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_product_isadmin"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="isAdmin",),
    ]
