# Generated by Django 4.1.2 on 2022-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_remove_product_isadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isAuction",
            field=models.BooleanField(default=False),
        ),
    ]
