# Generated by Django 4.1.2 on 2022-12-06 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_product_isauction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="when",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 6, 4, 7, 31, 573944)
            ),
        ),
    ]
