# Generated by Django 4.1.2 on 2022-12-06 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_product_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="when",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 6, 4, 9, 28, 208561, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
