# Generated by Django 4.1.2 on 2022-12-06 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_product_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="endDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 6, 8, 46, 7, 546387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
